#
# Changes the deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - auth-sealed-secret.yaml
images:
  - name: quay.io/nexodus/apiserver
    newTag: f0303a7ff021491e71d34bc38e80dfff26f93fcb
  - name: quay.io/nexodus/envsubst
    newTag: f0303a7ff021491e71d34bc38e80dfff26f93fcb
  - name: quay.io/nexodus/frontend
    newTag: f0303a7ff021491e71d34bc38e80dfff26f93fcb
  - name: quay.io/nexodus/go-ipam
    newTag: f0303a7ff021491e71d34bc38e80dfff26f93fcb
