apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - literals:
      - APIPROXY_OIDC_URL=https://auth.try.nexodus.127.0.0.1.nip.io/realms/nexodus
      - APIPROXY_OIDC_BACKCHANNEL=https://auth:8443/realms/nexodus
      - APIPROXY_API_DOMAIN=api.try.nexodus.127.0.0.1.nip.io
      - APIPROXY_API_URL=https://api.try.nexodus.127.0.0.1.nip.io
      - APIPROXY_WEB_DOMAIN=try.nexodus.127.0.0.1.nip.io
      - APIPROXY_WEB_ORIGINS=https://try.nexodus.127.0.0.1.nip.io
      - ENVOY_COMP_LOG_LEVEL=upstream:info,http:debug,router:debug,jwt:debug
    name: apiproxy
  - files:
      - files/envoy.yaml
      - files/sds_config.yaml
    name: apiproxy-envoy-config
resources:
  - deployment.yaml
  - ingress-api.yaml
  - ingress-frontend.yaml
  - service-admin.yaml
  - service-web.yaml
  - certificate-api.yaml
  - certificate-frontend.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: apiproxy
      app.kubernetes.io/instance: apiproxy
      app.kubernetes.io/name: apiproxy
